name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  app:
    runs-on: ubuntu-latest
    container: node:lts-stretch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        working-directory: app
        run: yarn install --frozen-lockfile
      - name: Lint
        working-directory: app
        run: yarn run lint

  actions-server:
    runs-on: ubuntu-latest
    container: node:lts-stretch
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Use Node.js ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Install dependencies
        working-directory: actions-server
        run: yarn install --frozen-lockfile
      - name: Lint
        working-directory: actions-server
        run: yarn run lint