name: lint
on: [push]
jobs:
  app:
    runs-on: ubuntu-latest
    container: node:12.16.3-stretch
    services:
      postgres:
        image: postgres:11
        volumes:
          - db_data:/var/lib/postgresql/data
        env:
          POSTGRES_PASSWORD: postgrespassword
#      actions-server:
#        image: node:12.16.3-stretch
#        env:
#          PORT: 3001
#        options: --entrypoint "/bin/sh -c yarn run start"
      graphql-engine:
        image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
        env:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
          HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
          HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
          HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
          ACTION_BASE_ENDPOINT: http://actions-server:3001
          HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "FAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKE"}'
        volumes:
          - /graphql-server/migrations:/hasura-migrations
          - /graphql-server/metadata:/hasura-metadata
    defaults:
      run:
        working-directory: app
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate GraphQL code
        run: yarn run gql-gen
      - name: Lint
        run: yarn run lint
