name: lint
on: [push]
jobs:
  app:
    runs-on: ubuntu-latest
    container: node:12.16.3-stretch
    env:
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    services:
      postgres:
        image: postgres:11
        volumes:
          - db_data:/var/lib/postgresql/data
        env:
          POSTGRES_PASSWORD: postgrespassword
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
#      actions-server:
#        image: node:12.16.3-stretch
#        env:
#          PORT: 3001
#        options: --entrypoint "/bin/sh -c yarn run start"
      graphql-engine:
        image: hasura/graphql-engine:v1.2.1
        env:
          HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
          HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
          HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
          HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
#          ACTION_BASE_ENDPOINT: http://actions-server:3001
          HASURA_GRAPHQL_JWT_SECRET: '{"type":"HS256", "key": "FAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKEFAKE"}'
        options: >-
          --health-cmd "wget --quiet --tries=1 --spider http://localhost:8080/healthz || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Apply Hasura migrations
        uses: tibotiber/hasura-action@master
        with:
          args: migrate apply
        env:
          HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
          HASURA_ADMIN_SECRET: ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_WORKDIR: graphql-server
      - name: Apply Hasura metadata
        uses: tibotiber/hasura-action@master
        with:
          args: metadata apply
        env:
          HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
          HASURA_ADMIN_SECRET: ${{ env.HASURA_GRAPHQL_ADMIN_SECRET }}
          HASURA_WORKDIR: graphql-server
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: app
      - name: Generate GraphQL code
        env:
          DEBUG: 1
          REACT_APP_FISHBOWL_GRAPHQL_ENDPOINT: http://graphql-engine:8080/v1/graphql
        run: yarn run gql-gen
        working-directory: app
      - name: Lint
        run: yarn run lint
        working-directory: app
